version: '3.8'
services:
  node1:
    build: .
    environment:
      - DFS_ID=node1
      - DFS_RAFT=node1:12000
      - DFS_GRPC=:13000
      - DFS_DATA=/data
      - DFS_PEERS=node2:12001,node3:12002
    networks:
      dfsnet:
        aliases: [node1]
    volumes:
      - node1-data:/data
    ports:
      - "13001:13000"
  node2:
    build: .
    environment:
      - DFS_ID=node2
      - DFS_RAFT=node2:12001
      - DFS_GRPC=:13000
      - DFS_DATA=/data
      - DFS_PEERS=node1:12000,node3:12002
    networks:
      dfsnet:
        aliases: [node2]
    volumes:
      - node2-data:/data
    ports:
      - "13002:13000"
  node3:
    build: .
    environment:
      - DFS_ID=node3
      - DFS_RAFT=node3:12002
      - DFS_GRPC=:13000
      - DFS_DATA=/data
      - DFS_PEERS=node1:12000,node2:12001
    networks:
      dfsnet:
        aliases: [node3]
    volumes:
      - node3-data:/data
    ports:
      - "13003:13000"
networks:
  dfsnet:
volumes:
  node1-data:
  node2-data:
  node3-data:
