version: '3.8'
services:
  node1:
    build: .
    command: ["-id","node1","-raft","node1:12000","-grpc",":13000","-data","/data","-peers","node2:12001,node3:12002"]
    networks:
      dfsnet:
        aliases: [node1]
    volumes:
      - node1-data:/data
    ports:
      - "13001:13000"
  node2:
    build: .
    command: ["-id","node2","-raft","node2:12001","-grpc",":13000","-data","/data","-peers","node1:12000,node3:12002"]
    networks:
      dfsnet:
        aliases: [node2]
    volumes:
      - node2-data:/data
    ports:
      - "13002:13000"
  node3:
    build: .
    command: ["-id","node3","-raft","node3:12002","-grpc",":13000","-data","/data","-peers","node1:12000,node2:12001"]
    networks:
      dfsnet:
        aliases: [node3]
    volumes:
      - node3-data:/data
    ports:
      - "13003:13000"
networks:
  dfsnet:
volumes:
  node1-data:
  node2-data:
  node3-data:
