name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Build
        run: go build -o dfs ./cmd/dfs
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: dfs
