name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test-bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Go Vet
        run: go vet ./...
      - name: Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck ./...
      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --disable errcheck --disable staticcheck
      - name: Govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest && govulncheck ./...
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
      - name: Benchmarks
        run: go test -bench . -benchmem ./...
