name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test-bench:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./... -cover
      - name: Benchmarks
        run: go test -bench . -benchmem ./...
